language: ruby
sudo: false
rvm:
  - 1.8.7
  - ree
  - 1.9.3
  - 2.0
  - 2.1
matrix:
before_install:
  - gem update --system --conservative || gem install --conservative bundler -v '<2'
before_script:
  - rake compile
